### ISSUE TITLE
I change some code for pynat to suite for python2.7, do you want commit these changes?

### ISSUE THREAD

**Issue by nomnom-btc** [arantonitis/pynat#1]
I have fork your pynat project to github.com/nomnom-btc/pynat

pynat current supports both python 3.x and python 2.7 now. all changes exist in one file (pynat.py), please refer to https://github.com/nomnom-btc/pynat/blob/master/pynat.py for details.

**Comment by aarant** [comment]
Yeah sure, I'll pull the changes in and update the package on PyPI. Thanks!

**Comment by aarant** [comment]
Updated.
